ML-Pipe_Line


Encoder

1.LableEncoder

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [3]:

#syntex
#from sklearn.preprocessing import LabelEncoder
#obj=LableEncoder()
#df['col_name'] = obj.fit_transform(df["col_name"])

LE=LabelEncoder()

df = pd.DataFrame({"gender":["Male","Female","male","Male","Female","other","other"]})
df

,gender
0,Male
1,Female
2,male
3,Male
4,Female
5,other
6,other


In [4]:
df['gender'] = LE.fit_transform(df['gender'])
df

,gender
0,1
1,0
2,2
3,1
4,0
5,3
6,3


2.ONE-HOT encoder


In [5]:
from sklearn.preprocessing import OneHotEncoder
OHE = OneHotEncoder(sparse_output=False)
df=pd.DataFrame({"Product":["Laptop","AC","AC","Mobile","Laptop","mobile"]})
data = OHE.fit_transform(df[["Product"]])
names=OHE.get_feature_names_out(["Product"])
df1=pd.DataFrame(data,columns=names)
df1["Product"]=df
df1



,Product_AC,Product_Laptop,Product_Mobile,Product_mobile,Product
0,0.0,1.0,0.0,0.0,Laptop
1,1.0,0.0,0.0,0.0,AC
2,1.0,0.0,0.0,0.0,AC
3,0.0,0.0,1.0,0.0,Mobile
4,0.0,1.0,0.0,0.0,Laptop
5,0.0,0.0,0.0,1.0,mobile


3. Ordinal encoder

In [6]:
from sklearn.preprocessing import OrdinalEncoder

In [7]:
df=pd.DataFrame({"salary":["Low","Medium","High","High","Medium","Low","Low"]})
OE=OrdinalEncoder(categories=[["Low","Medium","High"]])
df["salary"]=OE.fit_transform(df[["salary"]])
df

,salary
0,0.0
1,1.0
2,2.0
3,2.0
4,1.0
5,0.0
6,0.0


Feature Scaling

1.Normalization


In [8]:
from sklearn.preprocessing import Normalizer
df = pd.DataFrame({"Weight" : [65,80,75],
                   "Height":[170,130,110]})
df

,Weight,Height
0,65,170
1,80,130
2,75,110


In [9]:
from sklearn.preprocessing import Normalizer
norm=Normalizer()
data=norm.fit_transform(df)
df3=pd.DataFrame(data,columns=df.columns)
df3

,Weight,Height
0,0.357137,0.934052
1,0.524097,0.851658
2,0.563337,0.826227


In [10]:
#ASSIGNMENT
from sklearn.preprocessing import Normalizer
df = pd.DataFrame({"HRS" : [2,6,8,1,4],
                   "USAGE":[800,3500,5060,500,2000]})
df

,HRS,USAGE
0,2,800
1,6,3500
2,8,5060
3,1,500
4,4,2000


In [11]:
norm=Normalizer()
data=norm.fit_transform(df)
df4=pd.DataFrame(data,columns=df.columns)
df4

,HRS,USAGE
0,0.002500,0.999997
1,0.001714,0.999999
2,0.001581,0.999999
3,0.002000,0.999998
4,0.002000,0.999998


Standard Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
SS=StandardScaler()
df = pd.DataFrame({"Weight" : [65,80,75],
                   "Height":[170,130,110]})
df

,Weight,Height
0,65,170
1,80,130
2,75,110


In [13]:
data=SS.fit_transform(df)
df5=pd.DataFrame(data,columns=df.columns)
df5


,Weight,Height
0,-1.336306,1.336306
1,1.069045,-0.267261
2,0.267261,-1.069045


Linear Regression


In [14]:
#importing necessary lib
import pandas as pd
from sklearn.linear_model import LinearRegression,Ridge,Lasso
# sklearn--> library
# linear_model-->module
# LinearRegression --> class
# importing perfamance martics those are  r2_score,mean_absolute_error
from sklearn.metrics import r2_score,mean_absolute_error
# for splitting data set into training and testing data set we use
from sklearn.model_selection import train_test_split

In [15]:
#load and printing data
# the data set is house prediction datat set
# Now we are solving regression problem
df=pd.read_csv("https://raw.githubusercontent.com/Jeevita-R/ML_datasets/refs/heads/main/House_price_prediction.csv")
df

,Unnamed: 0,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.000000,160.2564,1480000.0
1,2,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,0.0,156.000000,79.0000,1035000.0
2,4,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,0.0,134.000000,150.0000,1465000.0
3,5,Abbotsford,3,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,1.0,94.000000,160.2564,850000.0
4,6,Abbotsford,4,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,1.0,2.0,120.000000,142.0000,1600000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27239,34852,Yarraville,4,h,PI,Jas,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,4.0,1.0,3.0,593.000000,160.2564,1480000.0
27240,34853,Yarraville,2,h,SP,Sweeney,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,2.0,1.0,98.000000,104.0000,888000.0
27241,34854,Yarraville,2,t,S,Jas,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,1.0,2.0,220.000000,120.0000,705000.0
27242,34855,Yarraville,3,h,SP,hockingstuart,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,0.0,0.0,0.0,593.598993,160.2564,1140000.0


In [16]:
#what type of data  we have
df.info()
#object datatype --> str,disc,set

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27244 entries, 0 to 27243
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Unnamed: 0     27244 non-null  int64  
 1   Suburb         27244 non-null  object 
 2   Rooms          27244 non-null  int64  
 3   Type           27244 non-null  object 
 4   Method         27244 non-null  object 
 5   SellerG        27244 non-null  object 
 6   Regionname     27244 non-null  object 
 7   Propertycount  27244 non-null  float64
 8   Distance       27244 non-null  float64
 9   CouncilArea    27244 non-null  object 
 10  Bedroom2       27244 non-null  float64
 11  Bathroom       27244 non-null  float64
 12  Car            27244 non-null  float64
 13  Landsize       27244 non-null  float64
 14  BuildingArea   27244 non-null  float64
 15  Price          27244 non-null  float64
dtypes: float64(8), int64(2), object(6)
memory usage: 3.3+ MB


In [17]:
df.head()
#top 5 rows


,Unnamed: 0,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.0,160.2564,1480000.0
1,2,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,0.0,156.0,79.0000,1035000.0
2,4,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,0.0,134.0,150.0000,1465000.0
3,5,Abbotsford,3,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,1.0,94.0,160.2564,850000.0
4,6,Abbotsford,4,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,1.0,2.0,120.0,142.0000,1600000.0


In [18]:
df.tail()#last rows

,Unnamed: 0,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
27239,34852,Yarraville,4,h,PI,Jas,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,4.0,1.0,3.0,593.000000,160.2564,1480000.0
27240,34853,Yarraville,2,h,SP,Sweeney,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,2.0,1.0,98.000000,104.0000,888000.0
27241,34854,Yarraville,2,t,S,Jas,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,1.0,2.0,220.000000,120.0000,705000.0
27242,34855,Yarraville,3,h,SP,hockingstuart,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,0.0,0.0,0.0,593.598993,160.2564,1140000.0
27243,34856,Yarraville,2,h,PI,RW,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,1.0,0.0,250.000000,103.0000,1020000.0


In [19]:
#drop innecessary colum
df=df.drop(columns=["Unnamed: 0"],axis=1)
df
#axis=1 to remove entair column

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.000000,160.2564,1480000.0
1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,0.0,156.000000,79.0000,1035000.0
2,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,0.0,134.000000,150.0000,1465000.0
3,Abbotsford,3,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,1.0,94.000000,160.2564,850000.0
4,Abbotsford,4,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,1.0,2.0,120.000000,142.0000,1600000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27239,Yarraville,4,h,PI,Jas,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,4.0,1.0,3.0,593.000000,160.2564,1480000.0
27240,Yarraville,2,h,SP,Sweeney,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,2.0,1.0,98.000000,104.0000,888000.0
27241,Yarraville,2,t,S,Jas,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,1.0,2.0,220.000000,120.0000,705000.0
27242,Yarraville,3,h,SP,hockingstuart,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,0.0,0.0,0.0,593.598993,160.2564,1140000.0


In [20]:
# here we conver the object to one hot encoder
#get_dummies -->work as one-hot encodder
#drop_first=True --> it will remove the first column in the one hot encoder, and it is optional to use
# it will reduce the no. of column
df=pd.get_dummies(df,drop_first=True,dtype=int)
df
# Suburb is removed

,Rooms,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price,Suburb_Aberfeldie,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
0,2,4019.0,2.5,2.0,1.0,1.0,202.000000,160.2564,1480000.0,0,...,0,0,0,0,0,0,0,0,1,0
1,2,4019.0,2.5,2.0,1.0,0.0,156.000000,79.0000,1035000.0,0,...,0,0,0,0,0,0,0,0,1,0
2,3,4019.0,2.5,3.0,2.0,0.0,134.000000,150.0000,1465000.0,0,...,0,0,0,0,0,0,0,0,1,0
3,3,4019.0,2.5,3.0,2.0,1.0,94.000000,160.2564,850000.0,0,...,0,0,0,0,0,0,0,0,1,0
4,4,4019.0,2.5,3.0,1.0,2.0,120.000000,142.0000,1600000.0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27239,4,6543.0,6.3,4.0,1.0,3.0,593.000000,160.2564,1480000.0,0,...,0,0,0,0,0,0,0,0,0,0
27240,2,6543.0,6.3,2.0,2.0,1.0,98.000000,104.0000,888000.0,0,...,0,0,0,0,0,0,0,0,0,0
27241,2,6543.0,6.3,2.0,1.0,2.0,220.000000,120.0000,705000.0,0,...,0,0,0,0,0,0,0,0,0,0
27242,3,6543.0,6.3,0.0,0.0,0.0,593.598993,160.2564,1140000.0,0,...,0,0,0,0,0,0,0,0,0,0


In [21]:
#slpiting the dataset into input and output
#input
x = df.drop("Price",axis=1)
x
# here except price column every other column will be assigned to variable x
# where x contain all input column

,Rooms,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Suburb_Aberfeldie,Suburb_Airport West,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
0,2,4019.0,2.5,2.0,1.0,1.0,202.000000,160.2564,0,0,...,0,0,0,0,0,0,0,0,1,0
1,2,4019.0,2.5,2.0,1.0,0.0,156.000000,79.0000,0,0,...,0,0,0,0,0,0,0,0,1,0
2,3,4019.0,2.5,3.0,2.0,0.0,134.000000,150.0000,0,0,...,0,0,0,0,0,0,0,0,1,0
3,3,4019.0,2.5,3.0,2.0,1.0,94.000000,160.2564,0,0,...,0,0,0,0,0,0,0,0,1,0
4,4,4019.0,2.5,3.0,1.0,2.0,120.000000,142.0000,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27239,4,6543.0,6.3,4.0,1.0,3.0,593.000000,160.2564,0,0,...,0,0,0,0,0,0,0,0,0,0
27240,2,6543.0,6.3,2.0,2.0,1.0,98.000000,104.0000,0,0,...,0,0,0,0,0,0,0,0,0,0
27241,2,6543.0,6.3,2.0,1.0,2.0,220.000000,120.0000,0,0,...,0,0,0,0,0,0,0,0,0,0
27242,3,6543.0,6.3,0.0,0.0,0.0,593.598993,160.2564,0,0,...,0,0,0,0,0,0,0,0,0,0


In [22]:
#output
y=df["Price"]
y
# here price column will be assigned for y

,Price
0,1480000.0
1,1035000.0
2,1465000.0
3,850000.0
4,1600000.0
...,...
27239,1480000.0
27240,888000.0
27241,705000.0
27242,1140000.0


In [23]:
# splitting into training and testing(70%-30%)
# test_size=0.3 size of test
# random_state=42 --> training data and testing data will be stable , means no changes will happen
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)


In [24]:
# performing Linear Regression
# traing the model
LR=LinearRegression()
LR.fit(xtrain,ytrain)
# the model is trained

LinearRegression()

In [25]:
#making the prediction
#ypred--> prediction variable
ypred=LR.predict(xtest)
ypred

array([ 857125.97565381, 1356220.62792179,  640137.72117794, ...,
        573352.74572779, 1057081.85294629,  832261.83044117])

In [26]:
# checking the efficiency of both traing and testing datat set
# to see it model is  giving the proper result
print("Training Efficiency:",LR.score(xtrain,ytrain))
print("Training Efficiency:",LR.score(xtest,ytest))

Training Efficiency: 0.6746078592844227
Training Efficiency: 0.6710114344343596


In [27]:
#performance matrices
#
print("R2 score:",r2_score(ytest,ypred) )
print("R2 score:",mean_absolute_error(ytest,ypred) )

R2 score: 0.6710114344343596
R2 score: 235042.66982074408


Ridge regression

In [28]:
ridge=Ridge(alpha=3)
ridge.fit(xtrain,ytrain)
# alpha=3--> in ridge it will give penalty to the cost function
# in place of lamda we use alpha=3

Ridge(alpha=3)

In [29]:
ypred=ridge.predict(xtest)
ypred

array([ 858975.99054429, 1353165.79084524,  655111.44633186, ...,
        576165.7396798 , 1063807.97779894,  840708.89035017])

In [30]:
print("Training Efficiency:",ridge.score(xtrain,ytrain))
print("Training Efficiency:",ridge.score(xtest,ytest))

Training Efficiency: 0.6725299343635871
Training Efficiency: 0.6798144534227779


In [31]:
print("R2 score:",r2_score(ytest,ypred) )
print("R2 score:",mean_absolute_error(ytest,ypred) )

R2 score: 0.6798144534227779
R2 score: 232195.687834101


Lasso Regression

In [32]:
lasso=Lasso(alpha=3)
lasso.fit(xtrain,ytrain)
# alpha=3--> in ridge it will give penalty to the cost function
# in place of lamda we use alpha=3

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.282e+15, tolerance: 7.845e+11
  model = cd_fast.enet_coordinate_descent(


Lasso(alpha=3)

In [33]:
ypred= lasso.predict(xtest)
ypred

array([ 857752.51132378, 1355224.43904117,  644172.8231605 , ...,
        574583.44948298, 1057974.21055141,  828554.76777646])

In [34]:
print("Training Efficiency:",lasso.score(xtrain,ytrain))
print("Training Efficiency:",lasso.score(xtest,ytest))

Training Efficiency: 0.6745199897085916
Training Efficiency: 0.6733086097628754


In [35]:
print("R2 score:",r2_score(ytest,ypred) )
print("R2 score:",mean_absolute_error(ytest,ypred) )

R2 score: 0.6733086097628754
R2 score: 234345.08267742503


Logistic Regression


In [36]:
#importing lib
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,f1_score
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer #importing the breast cancer from skleart

In [37]:
# reading from sklearn lib --> breast_cancer
# 1st create obj
dataset = load_breast_cancer()
dataset
#it is in dist and array formate

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [43]:
#convert it into data frame
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)
df
#no target col

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400


In [44]:
df["cancer"]=dataset.target
# where target is loaded to df
df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,cancer
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0


In [45]:
#splitting data into input and output
x=df.drop("cancer",axis=1)
y=df["cancer"]
x

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400


In [46]:
#again splitting data in train and test
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)


In [47]:
#model creation
model=LogisticRegression()
#model creation
model.fit(xtrain,ytrain)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [48]:
#makink predictions
ypred=model.predict(xtest)
ypred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1])

In [49]:
#checking the training and testing efficiency
print("training efficiency",model.score(xtrain,ytrain))
print("training efficiency",model.score(xtest,ytest))

training efficiency 0.9346733668341709
training efficiency 0.9707602339181286


confusion matrice




In [50]:
conf_matrx=confusion_matrix(ytest,ypred)
conf_matrx
#59 --> TP 107-->tn

array([[ 59,   4],
       [  1, 107]])

In [51]:
print("Accuracy score : ",accuracy_score(ytest,ypred))
print("Precision score : ",precision_score(ytest,ypred))
print("Recall score : ",recall_score(ytest,ypred))
print("F1 score : ",f1_score(ytest,ypred))



Accuracy score :  0.9707602339181286
Precision score :  0.963963963963964
Recall score :  0.9907407407407407
F1 score :  0.9771689497716894
