# ADA-BOOST classifiers

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import AdaBoostClassifier,AdaBoostRegressor
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,r2_score,mean_absolute_error
from sklearn.datasets import make_classification, make_regression# creating synthatic datasets--> random datat

In [ ]:
# we use n_classes=2 for classification
x,y=make_classification(n_samples=1000,n_features=5,n_classes=2,random_state=42)
# n_samples=1000 -->number of row in dataset
#n_features=5 --> how many featues we want in dataset--> we have 5 different data in input column
#n_classes=2 --> how many classes in output column in y we have "0" and "1"

In [ ]:
x

array([[-0.43964281,  0.54254734, -0.82241993,  0.40136622, -0.85484   ],
       [ 2.82223116, -2.48085944, -1.14769139, -2.10113103,  3.04027792],
       [ 1.61838572, -1.36947785, -2.08411294, -1.17965857,  1.61360231],
       ...,
       [ 1.56038977, -0.22904063, -0.2344078 , -0.61957623, -1.10985576],
       [ 0.88692467, -0.22294581, -1.3088204 , -0.39617745, -0.40427827],
       [-2.74710392,  1.85043021, -0.19382614,  1.77741855, -1.58083381]])

In [ ]:
y

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
base_model=DecisionTreeClassifier(max_depth=1)
model=AdaBoostClassifier(estimator=base_model,n_estimators=300,random_state=42)
model.fit(xtrain,ytrain)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1),
                   n_estimators=300, random_state=42)

In [ ]:
ypredc=model.predict(xtest)

In [ ]:
print("trining efficiency",model.score(xtrain,ytrain))
print("testing efficiency",model.score(xtest,ytest))

trining efficiency 0.9042857142857142
testing efficiency 0.87


In [ ]:
confusion_matrix(ytest,ypredc)

array([[135,  11],
       [ 28, 126]])

In [ ]:
print("precision_score:",precision_score(ytest,ypredc))
print("recall_score",recall_score(ytest,ypredc))

precision_score: 0.9197080291970803
recall_score 0.8181818181818182


# ADDABOOST Regression

In [ ]:
# we use n_informative=2 for regressions
x,y=make_regression(n_samples=1000,n_features=5,n_informative=2,random_state=42)
# n_samples=1000 -->number of row in dataset
#n_features=5 --> how many featues we want in dataset--> we have 5 different data in input column
#n_classes=2 --> how many classes in output column in y we have "0" and "1"

In [ ]:
x

array([[-0.62631528,  0.49406392, -2.85462666, -0.85685187, -1.12605396],
       [-0.02502696,  0.8177663 ,  1.39020755,  0.55781031,  0.01035262],
       [-1.42225371, -0.64657288, -1.081548  ,  1.68714164,  0.88163976],
       ...,
       [-2.0820987 ,  0.55314916, -0.5482003 ,  1.92344579, -0.77461497],
       [ 0.55832691,  0.07600539,  0.53875599, -0.92067359,  0.16936082],
       [ 1.67737709, -0.80517175,  1.07684814, -2.16967742, -1.1941894 ]])

In [ ]:
y

array([-1.15292357e+00,  1.51111782e+01, -3.62081754e+01, -1.03050758e+01,
        1.71316767e+00,  1.64526923e+01,  2.07794837e+01, -9.30345195e+00,
        2.68393050e+01, -1.64206933e+01, -5.85631612e+00, -9.20428786e+00,
       -2.17402654e+01,  8.71567510e+00,  8.06237825e+00, -1.72480134e+01,
       -2.24796104e+01, -1.42431431e+01,  3.08712378e+00, -1.46483960e+01,
        2.23226050e+01,  7.10845648e+00,  1.81463712e+01,  1.14173741e+01,
       -3.18012293e+01, -5.86388405e+01,  1.34949634e+01,  2.60556981e+01,
        3.31256878e+01,  4.25176019e+00, -1.06344700e+01,  2.13982268e+01,
        8.19965888e+00, -1.03942549e+01, -4.83488563e+01, -1.96592504e+01,
       -1.37062041e+01, -2.36953567e+01, -2.10339435e+01, -6.61098943e+00,
       -2.18091964e+01, -4.23000931e+01,  2.65562397e+01, -2.38328261e+01,
        6.26251580e+00, -1.08005080e+01, -2.47855820e+01,  4.61861614e+00,
        1.52215746e+01, -7.79347006e+01, -3.03105681e+01,  4.91923603e+01,
       -6.15530141e+00,  

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
base_model=DecisionTreeRegressor(max_depth=1)
modelr=AdaBoostRegressor(estimator=base_model,n_estimators=200,random_state=42)
modelr.fit(x_train,y_train)

AdaBoostRegressor(estimator=DecisionTreeRegressor(max_depth=1),
                  n_estimators=200, random_state=42)

In [ ]:
ypredr=modelr.predict(x_test)


In [ ]:
print("trining efficiency",modelr.score(x_train,y_train))
print("testing efficiency",modelr.score(x_test,y_test))

trining efficiency 0.7579278929805958
testing efficiency 0.7425294920959715


In [ ]:
# print("R2 score",r2_score(ytest, ypredr))
# print("MAE",mean_absolute_error(ytest, ypredr))
print("R2 score",r2_score(y_test, ypredr))
print("MAE",mean_absolute_error(y_test, ypredr))


R2 score 0.7425294920959715
MAE 10.31871885643376


# Gradient Boosting

# Gradient Boosting Regressor

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier,GradientBoostingRegressor
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,f1_score,recall_score,r2_score,mean_absolute_error


In [ ]:
df=pd.read_csv("/content/house_price_regression_dataset.csv")
df

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06
...,...,...,...,...,...,...,...,...
995,3261,4,1,1978,2.165110,2,10,7.014940e+05
996,3179,1,2,1999,2.977123,1,10,6.837232e+05
997,2606,4,2,1962,4.055067,0,2,5.720240e+05
998,4723,5,2,1950,1.930921,0,7,9.648653e+05


In [ ]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
x

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality
0,1360,2,1,1981,0.599637,0,5
1,4272,3,3,2016,4.753014,1,6
2,3592,1,2,2016,3.634823,0,9
3,966,1,2,1977,2.730667,1,8
4,4926,2,1,1993,4.699073,0,8
...,...,...,...,...,...,...,...
995,3261,4,1,1978,2.165110,2,10
996,3179,1,2,1999,2.977123,1,10
997,2606,4,2,1962,4.055067,0,2
998,4723,5,2,1950,1.930921,0,7


In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
modelr=GradientBoostingRegressor(n_estimators=300)
modelr.fit(xtrain,ytrain)

GradientBoostingRegressor(n_estimators=300)

In [ ]:
ypredr=modelr.predict(xtest)


In [ ]:
print("training efficiency :",modelr.score(xtrain,ytrain))
print("testing efficiency :",modelr.score(xtest,ytest))

training efficiency : 0.9995244930475269
testing efficiency : 0.9967855999516105


In [ ]:
print("r2 score",r2_score(ytest,ypredr))
print("MAE",mean_absolute_error(ytest,ypredr))

r2 score 0.9967855999516105
MAE 11570.462760126928


## GradientBoostingClassifier

In [ ]:
df1=pd.read_csv("/content/heart_disease.csv")
df1

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,...,Yes,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes
9996,38.0,Male,172.0,154.0,Medium,No,No,No,31.856801,Yes,...,Yes,NaN,High,8.247784,Low,377.0,83.0,2.658267,9.715709,Yes
9997,73.0,Male,152.0,201.0,High,Yes,No,Yes,26.899911,No,...,Yes,NaN,Low,4.436762,Low,248.0,88.0,4.408867,9.492429,Yes
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,...,Yes,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes


In [ ]:
df1.info()
#Heart Disease Status is the output column


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   object 
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   object 
 5   Smoking               9975 non-null   object 
 6   Family Heart Disease  9979 non-null   object 
 7   Diabetes              9970 non-null   object 
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   object 
 10  Low HDL Cholesterol   9975 non-null   object 
 11  High LDL Cholesterol  9974 non-null   object 
 12  Alcohol Consumption   7414 non-null   object 
 13  Stress Level          9978 non-null   object 
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption   

In [ ]:
df1.isnull().sum() # to know the count of nul value

,0
Age,29
Gender,19
Blood Pressure,19
Cholesterol Level,30
Exercise Habits,25
Smoking,25
Family Heart Disease,21
Diabetes,30
BMI,22
High Blood Pressure,26


In [ ]:
df1.duplicated().sum() # to know the count of duplicated value here no duplicate

np.int64(0)

In [ ]:

#droping the rows
# using dropna()
df1.dropna(inplace=True)

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7067 entries, 1 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Age                   7067 non-null   float64
 1   Gender                7067 non-null   object 
 2   Blood Pressure        7067 non-null   float64
 3   Cholesterol Level     7067 non-null   float64
 4   Exercise Habits       7067 non-null   object 
 5   Smoking               7067 non-null   object 
 6   Family Heart Disease  7067 non-null   object 
 7   Diabetes              7067 non-null   object 
 8   BMI                   7067 non-null   float64
 9   High Blood Pressure   7067 non-null   object 
 10  Low HDL Cholesterol   7067 non-null   object 
 11  High LDL Cholesterol  7067 non-null   object 
 12  Alcohol Consumption   7067 non-null   object 
 13  Stress Level          7067 non-null   object 
 14  Sleep Hours           7067 non-null   float64
 15  Sugar Consumption     7067

In [ ]:
df.isnull().sum()

,0
Square_Footage,0
Num_Bedrooms,0
Num_Bathrooms,0
Year_Built,0
Lot_Size,0
Garage_Size,0
Neighborhood_Quality,0
House_Price,0


In [ ]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder
LE=LabelEncoder()
OE=OrdinalEncoder(categories=[["Low","Medium","High"]])


In [ ]:
df1.columns

Index(['Age', 'Gender', 'Blood Pressure', 'Cholesterol Level',
       'Exercise Habits', 'Smoking', 'Family Heart Disease', 'Diabetes', 'BMI',
       'High Blood Pressure', 'Low HDL Cholesterol', 'High LDL Cholesterol',
       'Alcohol Consumption', 'Stress Level', 'Sleep Hours',
       'Sugar Consumption', 'Triglyceride Level', 'Fasting Blood Sugar',
       'CRP Level', 'Homocysteine Level', 'Heart Disease Status'],
      dtype='object')

In [ ]:
for col in df1.columns:
  if df1[col].dtype == object:
    if 'High' in df1[col].unique():
      df1[col]=OE.fit_transform(df1[[col]])
    else:
      df1[col]=LE.fit_transform(df1[[col]])
df1


/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
1,69.0,0,146.0,286.0,2.0,0,1,1,25.221799,0,...,0,1.0,2.0,8.744034,1.0,133.0,157.0,9.355389,19.298875,0
2,46.0,1,126.0,216.0,0.0,0,0,0,29.855447,0,...,1,0.0,0.0,4.440440,0.0,393.0,92.0,12.709873,11.230926,0
3,32.0,0,122.0,293.0,2.0,1,1,0,24.130477,1,...,1,0.0,2.0,5.249405,2.0,293.0,94.0,12.509046,5.961958,0
4,60.0,1,166.0,242.0,0.0,1,1,1,20.486289,1,...,0,0.0,2.0,7.030971,2.0,263.0,154.0,10.381259,8.153887,0
5,25.0,1,152.0,257.0,0.0,1,0,0,28.144681,0,...,0,0.0,1.0,5.504876,0.0,126.0,91.0,4.297575,10.815983,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,68.0,0,169.0,291.0,1.0,1,0,0,22.839718,0,...,0,1.0,0.0,6.057509,2.0,299.0,142.0,3.321020,11.910244,1
9994,73.0,0,144.0,191.0,1.0,1,1,1,39.459620,0,...,0,1.0,0.0,7.549114,1.0,200.0,88.0,1.154904,8.021732,1
9995,25.0,0,136.0,243.0,1.0,1,0,0,18.788791,1,...,1,1.0,2.0,6.834954,1.0,343.0,133.0,3.588814,19.132004,1
9998,23.0,1,142.0,299.0,0.0,1,0,1,34.964026,1,...,1,1.0,2.0,8.526329,1.0,113.0,153.0,7.215634,11.873486,1


In [ ]:
x=df1.iloc[:,:-1]
y=df1.iloc[:,-1]


In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() # Create an instance of StandardScaler
data = scaler.fit_transform(xtrain)
df5=pd.DataFrame(data,columns=x.columns)
df5

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,Low HDL Cholesterol,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level
0,1.239462,-1.015897,-1.476734,0.534330,1.224701,-1.030802,0.999192,1.009344,-0.852451,-1.015075,-1.000404,-0.976420,0.006941,0.005258,1.545955,1.230623,1.589997,-0.290649,-0.392684,1.642103
1,-0.726821,-1.015897,-1.247402,0.442143,-1.233149,0.970119,-1.000809,1.009344,1.352660,0.985149,0.999596,-0.976420,-1.219197,1.243679,1.330777,0.017174,-1.504389,-0.714629,-1.398527,-0.880437
2,-1.273010,0.984352,0.873915,0.949168,-1.233149,0.970119,-1.000809,-0.990742,0.794097,-1.015075,0.999596,-0.976420,1.233080,0.005258,-0.975424,1.230623,0.980322,0.557312,1.027627,0.106965
3,-0.344488,-1.015897,-1.362068,-0.594952,-1.233149,-1.030802,0.999192,1.009344,0.145193,-1.015075,0.999596,-0.976420,1.233080,-1.233163,1.493719,0.017174,0.267118,1.235681,-0.787552,-0.717707
4,-0.126012,-1.015897,0.759249,1.041354,-0.004224,-1.030802,0.999192,1.009344,-0.109310,0.985149,0.999596,1.024149,-1.219197,1.243679,0.327183,1.230623,-1.216807,1.150885,0.709063,0.824396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4941,0.037845,0.984352,1.045914,-0.525812,-1.233149,0.970119,-1.000809,1.009344,-1.158943,0.985149,0.999596,-0.976420,-1.219197,1.243679,-0.802765,-1.196275,1.221891,0.642108,-0.672789,-0.325180
4942,0.474796,-1.015897,1.217913,1.617518,-0.004224,-1.030802,0.999192,-0.990742,0.154687,0.985149,-1.000404,1.024149,-1.219197,0.005258,1.649939,0.017174,-0.077981,-1.138609,-1.670878,0.189903
4943,-1.436867,-1.015897,-0.272743,1.548378,1.224701,0.970119,0.999192,1.009344,-0.781243,0.985149,0.999596,-0.976420,-1.219197,1.243679,0.562305,1.230623,1.566990,0.048536,0.839439,0.681391
4944,0.638653,0.984352,0.759249,-0.848464,-0.004224,-1.030802,-1.000809,-0.990742,1.203634,0.985149,-1.000404,-0.976420,0.006941,-1.233163,-0.294298,-1.196275,0.508687,-1.562590,-0.107278,0.213598


In [ ]:
modelc=GradientBoostingClassifier(n_estimators=200,learning_rate=0.02)
modelc.fit(xtrain,ytrain)


GradientBoostingClassifier(learning_rate=0.02, n_estimators=200)

In [ ]:
ypredc=modelc.predict(xtest)
ypredc

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
print("trining accuracy",modelc.score(xtrain,ytrain))
print("testing accuracy",modelc.score(xtest,ytest))


trining accuracy 0.8020622725434695
testing accuracy 0.7901933050447902


In [ ]:
print("presicion score",precision_score(ytest,ypredc))
print("recall score",recall_score(ytest,ypredc))

presicion score 0.5
recall score 0.0022471910112359553


## X-G BOOST

# Classifier

In [ ]:
import pandas as pd
from sklearn.datasets import load_iris
from xgboost import XGBClassifier,XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,r2_score

In [ ]:
data=load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
df=pd.DataFrame(data.data,columns=data.feature_names)
df['target']=data.target
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [ ]:
x=df.drop('target',axis=1)
y=df.target

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
modelc=XGBClassifier(n_estimators=100,learning_rate=0.01,max_depth=5,random_state=42)
modelc.fit(xtrain,ytrain)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.01, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
ypredc=modelc.predict(xtest)
ypredc

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [ ]:
print("trining accuracy",modelc.score(xtrain,ytrain))
print("testing accuracy",modelc.score(xtest,ytest))

trining accuracy 0.9714285714285714
testing accuracy 1.0


In [ ]:
print("accuracy score",accuracy_score(ytest,ypredc))

accuracy score 1.0


# Regressor

In [ ]:
df1=pd.read_csv(" https://raw.githubusercontent.com/Jeevita-R/ML_datasets/refs/heads/main/Fetch_california_housing.csv")
df1

,Unnamed: 0,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...,...
20635,20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847


In [ ]:
df=df1.drop("Unnamed: 0", axis=1)
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847


In [ ]:
x=df.drop('target',axis=1)
y=df.target
x

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32


In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() # Create an instance of StandardScaler
xtrain_scaled = scaler.fit_transform(xtrain)
xtest_scaled = scaler.transform(xtest) # Correctly transform xtest
df5 = pd.DataFrame(xtrain_scaled, columns=x.columns) # Use xtrain_scaled
df5

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,0.133506,0.509357,0.181060,-0.273850,-0.184117,-0.010825,-0.805682,0.780934
1,-0.532218,-0.679873,-0.422630,-0.047868,-0.376191,-0.089316,-1.339473,1.245270
2,0.170990,-0.362745,0.073128,-0.242600,-0.611240,-0.044800,-0.496645,-0.277552
3,-0.402916,-1.155565,0.175848,-0.008560,-0.987495,-0.075230,1.690024,-0.706938
4,-0.299285,1.857152,-0.259598,-0.070993,0.086015,-0.066357,0.992350,-1.430902
...,...,...,...,...,...,...,...,...
14443,1.308827,0.509357,0.281603,-0.383849,-0.675265,-0.007030,-0.875918,0.810891
14444,-0.434100,0.350793,0.583037,0.383154,0.285105,0.063443,-0.763541,1.075513
14445,-0.494787,0.588640,-0.591570,-0.040978,0.287736,0.017201,-0.758858,0.601191
14446,0.967171,-1.076283,0.390149,-0.067164,0.306154,0.004821,0.903385,-1.186252


In [ ]:
modelr=XGBRegressor(n_estimators=400,learning_rate=0.01,max_depth=10,random_state=42)
modelr.fit(xtrain,ytrain)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.01, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=10,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=400,
             n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
ypredr=modelr.predict(xtest)
ypredr

array([0.53363776, 0.797851  , 4.8694043 , ..., 2.4090693 , 1.4668664 ,
       2.1262255 ], dtype=float32)

In [ ]:
print("trining accuracy",modelr.score(xtrain,ytrain))
print("testing accuracy",modelr.score(xtest,ytest))
print("r2 score",r2_score(ytest,ypredr))

trining accuracy 0.9559793816980929
testing accuracy 0.8200826351787331
r2 score 0.8200826351787331
